name: Deploy Next.js site to Pages
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Get code
        uses: action/checout@v3
      - name: install dependensis
        run: npm ci
      - name: Build project
        run: npm run dev 
