name: Deploy Next.js site to Pages
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Get code
        uses: actions/checkout@v4
      - name: point
        run: ls -la
      - name: Build project
        run: node -v
